# -*- coding: utf-8 -*-
"""Master_Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YiDhn7YE-NWWamWxidxJ07ggHK0SHEwA
"""

!pip install pymupdf pandas

"""Chunker"""

import os
import re
import fitz  # PyMuPDF
import pandas as pd

# ==========================================
# HELPER FUNCTIONS (Formatting & Cleaning)
# ==========================================
def compress_string(text: str) -> str:
    """
    The String Compression Rule.
    Aggressively strips all whitespace, newlines, and lowercases the string.
    This neutralizes EDGAR formatting artifacts to ensure our boundary detection
    is mathematically deterministic.
    """
    if pd.isna(text):
        return ""
    return re.sub(r'\s+', '', str(text)).lower()

def clean_footer_artifacts(text: str) -> str:
    """
    The Regex Scrub.
    Searches the extracted payload and permanently deletes physical page footers.
    This prevents token saturation and hallucinations in the Phase 1 LLM agents.
    """
    if not isinstance(text, str):
        return ""

    # (?i) makes it case-insensitive
    # \s* handles unpredictable spacing injected by the PDF conversion
    # [-–] captures both standard hyphens and en-dashes
    cleaned_text = re.sub(r'(?i)CREDIT AGREEMENT\s*[-–]\s*Page\s*\d+', '', text)

    # We run a final strip to ensure we don't leave floating empty lines at the end
    return cleaned_text.strip()

def calculate_printed_end_page(df: pd.DataFrame) -> pd.DataFrame:
    """
    Applies the sequential logic to calculate Printed_End_Page, handles the
    final document row mathematically, and explicitly reorders the dataframe columns.
    """
    df = df.copy()

    # 1. Vectorized Shift
    df['Printed_End_Page'] = df['Printed_Start_Page'].shift(-1)

    # 2. Handle the final row edge case mathematically
    last_idx = df.index[-1]
    abs_start = df.loc[last_idx, 'Absolute_Start_Page']
    abs_end = df.loc[last_idx, 'Absolute_End_Page']
    printed_start = df.loc[last_idx, 'Printed_Start_Page']

    page_delta = abs_end - abs_start
    df.loc[last_idx, 'Printed_End_Page'] = printed_start + page_delta

    # Clean up typing so it displays cleanly in the CSV (no floats)
    df['Printed_End_Page'] = df['Printed_End_Page'].astype(int)

    # 3. Column Reordering (Injecting right after Printed_Start_Page)
    cols = list(df.columns)
    cols.remove('Printed_End_Page')
    start_idx = cols.index('Printed_Start_Page')
    cols.insert(start_idx + 1, 'Printed_End_Page')

    return df[cols]

# ==========================================
# PASS 1: The Simplified TOC Skeleton
# ==========================================
def build_simplified_skeleton(pdf_path: str, max_toc_pages: int = 20) -> pd.DataFrame:
    print("Pass 1: Building TOC Skeleton...")
    doc = fitz.open(pdf_path)

    full_text_buffer = ""
    for page_num in range(min(max_toc_pages, len(doc))):
        full_text_buffer += doc[page_num].get_text("text") + "\n"

    clean_buffer = re.sub(r"\.{2,}", " ", full_text_buffer)
    clean_buffer = re.sub(r'","', ' ', clean_buffer).replace('"', '')

    toc_pattern = re.compile(
        r"(?P<type>Article|Section)\s+(?P<num>\d+(?:\.\d+)?)\.?\s+(?P<title>.{1,200}?)\s+(?P<page>\d+)(?=\n|$)",
        re.IGNORECASE | re.DOTALL
    )

    matches = toc_pattern.finditer(clean_buffer)

    skeleton_data = []
    current_article = "Preamble"
    current_article_title = "Document Front Matter"
    highest_page_seen = 0

    for match in matches:
        item_type = match.group("type").title().strip()
        num = match.group("num")
        title = match.group("title").replace("\n", " ").strip()
        page = int(match.group("page"))

        if page < (highest_page_seen - 2):
            print(f"   -> TOC boundary detected. Stopping scan.")
            break

        highest_page_seen = max(highest_page_seen, page)

        if item_type == "Article":
            current_article = f"Article {num}"
            current_article_title = title
        elif item_type == "Section":
            skeleton_data.append({
                "Article": current_article,
                "Article_Title": current_article_title,
                "Section": f"Section {num}",
                "Section_Title": title,
                "Printed_Start_Page": page
            })

    return pd.DataFrame(skeleton_data)


# ==========================================
# PASS 1.5: The Continuous Ribbon Page Map
# ==========================================
def build_page_spread_map(pdf_path: str) -> dict:
    print("Pass 1.5: Building Page Spread Map...")
    doc = fitz.open(pdf_path)
    footer_pattern = re.compile(r"(?:page\s*|^\s*-?\s*)(\d+)(?:\s*-?\s*$)", re.IGNORECASE)

    # --- MANUAL EDGE CASE INJECTION ---
    spread_data = [{
        "Printed_Page": 1,
        "Absolute_Start_Page": 11,
        "Absolute_End_Page": 12
    }]

    # State tracking starts at 12 to properly calculate Page 2
    last_known_end = 12

    # Start scanning for footers AFTER the TOC (e.g., skip the first 10 pages)
    # This completely prevents "TOC Bleed" from corrupting the sequential chain.
    for page_num in range(10, len(doc)):
        absolute_page = page_num + 1
        lines = doc[page_num].get_text("text").split('\n')

        for line in reversed(lines):
            line_stripped = re.sub(r'\s+', ' ', line).strip()
            if not line_stripped:
                continue

            match = footer_pattern.search(line_stripped)
            if match:
                printed_page = int(match.group(1))

                if not any(d['Printed_Page'] == printed_page for d in spread_data):
                    absolute_start = last_known_end + 1

                    spread_data.append({
                        "Printed_Page": printed_page,
                        "Absolute_Start_Page": absolute_start,
                        "Absolute_End_Page": absolute_page
                    })

                    last_known_end = absolute_page

                break

    df_map = pd.DataFrame(spread_data)
    return df_map.set_index('Printed_Page')[['Absolute_Start_Page', 'Absolute_End_Page']].to_dict('index')


# ==========================================
# PASS 2: The Targeted Window Search
# ==========================================
def calculate_exact_boundaries(pdf_path: str, df_skeleton: pd.DataFrame, spread_map: dict, output_csv: str = "final_spatial_map.csv") -> pd.DataFrame:
    print("Pass 2: Executing Targeted Window Search...")
    doc = fitz.open(pdf_path)

    df_skeleton['Absolute_Start_Page'] = None

    for idx, row in df_skeleton.iterrows():
        section_target = str(row['Section']).strip()
        printed_page = row['Printed_Start_Page']

        spread = spread_map.get(printed_page)

        if not spread:
            future_pages = [p for p in spread_map.keys() if p > printed_page]
            abs_start = 1
            if future_pages:
                next_known_printed_page = min(future_pages)
                abs_end = spread_map[next_known_printed_page]['Absolute_Start_Page']
            else:
                abs_end = len(doc)
        else:
            abs_start = spread['Absolute_Start_Page']
            abs_end = spread['Absolute_End_Page']

        found_exact_page = False

        for page_num in range(abs_start - 1, abs_end):
            lines = doc[page_num].get_text("text").split('\n')

            for line in lines:
                # --- BULLETPROOF STRING COMPRESSION FIX ---
                target_compressed = section_target.replace(" ", "").lower()
                line_compressed = re.sub(r'\s+', '', line).lower()

                if target_compressed in line_compressed:
                    df_skeleton.at[idx, 'Absolute_Start_Page'] = page_num + 1
                    found_exact_page = True
                    break

            if found_exact_page:
                break

        if not found_exact_page:
            df_skeleton.at[idx, 'Absolute_Start_Page'] = abs_start

    df_skeleton['Absolute_Start_Page'] = df_skeleton['Absolute_Start_Page'].astype(int)

    df_skeleton['Absolute_End_Page'] = df_skeleton['Absolute_Start_Page'].shift(-1)
    df_skeleton['Absolute_End_Page'] = df_skeleton['Absolute_End_Page'].fillna(len(doc))
    df_skeleton['Absolute_End_Page'] = df_skeleton['Absolute_End_Page'].astype(int)

    final_columns = [
        'Article', 'Article_Title', 'Section', 'Section_Title',
        'Printed_Start_Page', 'Absolute_Start_Page', 'Absolute_End_Page'
    ]
    df_final = df_skeleton[final_columns]

    df_final.to_csv(output_csv, index=False)
    print(f"✅ Map Built! Spatial mapping saved to: {output_csv}")

    return df_final


# ==========================================
# PASS 3: The Production Extraction Pipeline
# ==========================================
def run_extraction_engine(pdf_path: str, df: pd.DataFrame, output_path: str):
    """
    The Main Pipeline. Iterates through the verified spatial map, extracts
    text using the Stream method, applies the Regex scrub, and exports the final CSVs.
    """
    print("Pass 3: Initializing Production Extraction Engine...")

    # Process dataframe directly from memory
    df = calculate_printed_end_page(df)

    # Open the PDF globally to avoid memory leaks
    doc = fitz.open(pdf_path)

    for idx, row in df.iterrows():
        # Adjusting from 1-indexed (CSV) to 0-indexed (PyMuPDF)
        start_page = int(row['Absolute_Start_Page']) - 1
        end_page = int(row['Absolute_End_Page']) - 1

        # Prepare the deterministic boundary strings
        current_section = compress_string(row['Section'])
        next_section = compress_string(df.loc[idx + 1, 'Section']) if idx + 1 < len(df) else None

        stream_buffer = []
        is_buffering = False
        section_completed = False

        print(f"Extracting {row['Section']} (Pages {start_page + 1} to {end_page + 1})...")

        # 1. Targeted Page Loading
        for page_num in range(start_page, end_page + 1):
            if page_num >= len(doc) or section_completed:
                break

            page = doc[page_num]
            text_lines = page.get_text("text").split('\n')

            # 2. Block-by-Block State Machine (Stream Method)
            for line in text_lines:
                line_compressed = compress_string(line)

                # Skip totally empty lines during the boundary check
                if not line_compressed:
                    # Still buffer the natural line break if we are actively buffering
                    if is_buffering:
                        stream_buffer.append(line)
                    continue

                # Trigger Condition (Turn On)
                if not is_buffering and current_section in line_compressed:
                    is_buffering = True

                # Halt Condition (Turn Off)
                if is_buffering and next_section and next_section in line_compressed:
                    is_buffering = False
                    section_completed = True
                    break # Break the line loop

                # Buffer the raw, uncompressed payload
                if is_buffering:
                    stream_buffer.append(line)

        # 3. Payload Sanitization & Storage
        raw_string = "\n".join(stream_buffer)
        clean_string = clean_footer_artifacts(raw_string)

        # Store in dataframe memory (Looping efficiently now!)
        df.at[idx, 'Raw_Text_Unscrubbed'] = raw_string
        df.at[idx, 'Raw_Text_Clean'] = clean_string

    # ---------------------------------------------------------
    # 4. EXPORT & GENERATE THE AI PAYLOAD (OUTSIDE THE LOOP)
    # ---------------------------------------------------------

    # Export the master Single Source of Truth (Silver Layer for Auditing)
    df.to_csv(output_path, index=False)

    # Drop the unscrubbed column to prevent accidental ingestion
    payload_df = df.drop(columns=['Raw_Text_Unscrubbed'])

    # Rename 'Raw_Text_Clean' to 'Raw_Text' for the Phase 1 routing script
    payload_df = payload_df.rename(columns={'Raw_Text_Clean': 'Raw_Text'})

    # Generate the new filename dynamically
    payload_path = output_path.replace('.csv', '_phase1_payload.csv')

    # Export the stripped-down, agent-ready file (Gold Layer)
    payload_df.to_csv(payload_path, index=False)

    print(f"\n✅ Pipeline Complete!")
    print(f" -> Master audit file saved to: '{output_path}'")
    print(f" -> AI Payload generated and saved to: '{payload_path}'")


# ==========================================
# PIPELINE EXECUTION
# ==========================================
if __name__ == "__main__":
    PDF_FILE = "Credit_Agreement_Hallador.pdf"
    SPATIAL_MAP_CSV = "final_spatial_map.csv"
    FINAL_COVENANTS_CSV = "final_extracted_covenants.csv"

    if not os.path.exists(PDF_FILE):
        print(f"Error: Missing '{PDF_FILE}' in the current directory.")
    else:
        # Pass 1 & 1.5: Mapping
        skeleton_df = build_simplified_skeleton(PDF_FILE)
        page_spread_dictionary = build_page_spread_map(PDF_FILE)

        # Pass 2: Boundaries (Generates final map and passes it directly into memory)
        final_mapping_df = calculate_exact_boundaries(
            PDF_FILE, skeleton_df, page_spread_dictionary, SPATIAL_MAP_CSV
        )

        # Pass 3: Extraction (Consumes memory dataframe, saves final Silver/Gold outputs once)
        run_extraction_engine(PDF_FILE, final_mapping_df, FINAL_COVENANTS_CSV)

"""Tier 1 Router"""

import pandas as pd
import re
import json
from typing import List, Dict, Any

# =====================================================================
# JSON CONFIGURATION SCHEMA DEFINITION
# =====================================================================
"""
The router requires an external JSON file (e.g., 'covenant_config.json').
It MUST follow this exact structure so the Python Matrix can parse it:

{
  "routing_rules": [
    {
      "target_name": "TotalLeverageRatio",
      "valid_zones": ["NEGATIVE COVENANTS", "FINANCIAL COVENANTS"],
      "section_title_triggers": ["Total Leverage Ratio", "Consolidated Leverage"]
    },
    {
      "target_name": "DebtIncurrence",
      "valid_zones": ["NEGATIVE COVENANTS", "FINANCIAL COVENANTS"],
      "section_title_triggers": ["^Debt$", "Indebtedness"]
    }
  ]
}
"""

# =====================================================================
# THE ROUTER ENGINE
# =====================================================================

class Tier1DeterministicRouter:
    """
    A deterministic routing engine that filters unstructured document chunks
    into strict AI extraction envelopes using boolean matrix logic.
    """

    def __init__(self, json_config_path: str):
        """
        Initializes the router by loading the rules from an external JSON file.
        This ensures the execution code never touches the business logic.
        """
        try:
            with open(json_config_path, 'r') as file:
                config_data = json.load(file)
                self.rules = config_data.get("routing_rules", [])

            if not self.rules:
                raise ValueError("JSON loaded, but 'routing_rules' array was empty or missing.")

        except FileNotFoundError:
            raise FileNotFoundError(f"CRITICAL ERROR: Could not find configuration file at {json_config_path}")

    def _sanitize_dataframe(self, df: pd.DataFrame) -> pd.DataFrame:
        """Ensures no NaN values break the string-matching algorithms."""
        df_clean = df.copy()
        for col in ['Article_Title', 'Section_Title', 'Raw_Text']:
            if col in df_clean.columns:
                df_clean[col] = df_clean[col].fillna('')
        return df_clean

    def _build_dispatch_envelope(self, target_name: str, description: str, row: pd.Series) -> Dict[str, Any]:
        """
        LAYER 3: The Dispatcher.
        Now includes the Definition_Guardrail and an upgraded, high-resolution Receipt.
        """

        # Build the high-resolution receipt string
        detailed_receipt = (
            f"PDF Pages {row.get('Absolute_Start_Page', 'N/A')}-{row.get('Absolute_End_Page', 'N/A')} "
            f"(Printed Pages {row.get('Printed_Start_Page', 'N/A')}-{row.get('Printed_End_Page', 'N/A')}) | "
            f"{row.get('Article', 'N/A')}: {row.get('Article_Title', 'N/A')} | "
            f"{row.get('Section', 'N/A')}: {row.get('Section_Title', 'Unknown Section')}"
        )

        return {
            "Agent": target_name,
            "Schema": f"{target_name}Schema",
            "Definition_Guardrail": description,
            "Receipt": detailed_receipt,          # <-- The upgraded line!
            "Payload_Text": row.get('Raw_Text', '')
        }

    def route_document(self, df: pd.DataFrame) -> List[Dict[str, Any]]:
        """
        LAYER 2: The Matrix Tagger.
        Executes Zone Bouncers, Section Snipers, Anti-Boilerplate, and Density Filters.
        """
        df = self._sanitize_dataframe(df)
        dispatch_queue = []

        for rule in self.rules:
            target = rule["target_name"]
            description = rule.get("description", "")

            # --- GATE A: The Zone Bouncer (Broad-Net OR Logic) ---
            zone_mask = df['Article_Title'].str.upper().apply(
                lambda article: any(zone.upper() in article for zone in rule["valid_zones"])
            )

            # --- GATE B: The Section Sniper (Strict OR Logic) ---
            regex_pattern = "|".join(rule["section_title_triggers"])
            trigger_mask = df['Section_Title'].str.contains(
                regex_pattern, flags=re.IGNORECASE, regex=True
            )

            # --- GATE C: The Anti-Boilerplate Filter ---
            blacklist_pattern = "intentionally omitted|left blank|reserved"
            body_mask = ~df['Raw_Text'].str.contains(
                blacklist_pattern, flags=re.IGNORECASE, regex=True
            )

            # --- GATE D: The Density Filter (False-Flag Protection) ---
            # If the text is shorter than 150 characters, it is highly likely a cross-reference,
            # a placeholder, or a definition pointing elsewhere. Drop it so Tier 2 can find the real text.
            density_mask = df['Raw_Text'].str.len() > 150

            # --- THE FINAL MATRIX FILTER ---
            # The chunk must survive ALL four gates to become an extraction envelope
            surviving_chunks = df[zone_mask & trigger_mask & body_mask & density_mask]

            # --- GATE E: The Singularity Gate & Dispatcher ---
            if len(surviving_chunks) == 1:
                # Perfect Match: Build envelope and append to queue
                row = surviving_chunks.iloc[0]
                envelope = self._build_dispatch_envelope(target, description, row)
                dispatch_queue.append(envelope)

            elif len(surviving_chunks) == 0:
                # True Negative / Missing Title
                print(f"[{target}] Tier 1 Failed (0 chunks). Cascading to Tier 2 Vector Search...")
                # (Logic to trigger Tier 2 goes here later)

            else:
                # Ambiguity Detected (>1 chunk)
                print(f"[{target}] Tier 1 Ambiguity ({len(surviving_chunks)} chunks). Cascading to Tier 2 Vector Search...")
                # (Logic to trigger Tier 2 goes here later)

        return dispatch_queue


# =====================================================================
# EXECUTION SCRIPT (Uncommented for actual use)
# =====================================================================
if __name__ == "__main__":

    # 1. Define your exact file paths
    CSV_FILE_PATH = 'final_extracted_covenants_phase1_payload.csv'
    JSON_CONFIG_PATH = 'covenant_config.json'

    try:
        # 2. Load the external CSV Data
        print(f"Loading data from {CSV_FILE_PATH}...")
        credit_agreement_df = pd.read_csv(CSV_FILE_PATH)

        # 3. Initialize the Router (It pulls the JSON file internally)
        print(f"Loading routing rules from {JSON_CONFIG_PATH}...")
        router = Tier1DeterministicRouter(json_config_path=JSON_CONFIG_PATH)

        # 4. Execute the Routing Engine
        print("Executing Matrix Filter...\n")
        ai_dispatch_queue = router.route_document(credit_agreement_df)

        # 5. Output and Save the results
        OUTPUT_FILE = 'dispatch_queue_output.json'

        # Open a new file in 'write' mode
        with open(OUTPUT_FILE, 'w') as outfile:
            # json.dump physically writes the list to the file with a clean 4-space indent
            json.dump(ai_dispatch_queue, outfile, indent=4)

        print(f"=== ROUTING COMPLETE ===")
        print(f"Successfully generated {len(ai_dispatch_queue)} LLM Extraction Envelopes.")
        print(f"File physically saved to: {OUTPUT_FILE}")

        # Look at the first envelope to verify it worked
        if ai_dispatch_queue:
            print("\nPreview of Envelope 1:")
            print(json.dumps(ai_dispatch_queue[0], indent=2))

    except Exception as e:
        print(f"\nPIPELINE FAILED: {e}")

"""Extraction Agents

Does not use parralel Extraction yet due to Free tier of API. Does not use Tournament style Extraction yet due to Free tier of API.
"""

# Install the official Google GenAI SDK and ensure Pydantic is up to date
!pip install -q google-genai pydantic

import os
from google.colab import userdata
from google import genai
from pydantic import BaseModel, Field
from typing import List, Optional, Union

# Initialize the client using Colab's Secret Manager
# This securely fetches your saved key without exposing it in the notebook
os.environ["GEMINI_API_KEY"] = userdata.get('FreeTierGeminKey')
client = genai.Client()

"""Defining the Extraction Agents"""

from pydantic import BaseModel, Field
from typing import List, Optional, Union

# ==========================================
# 1. THE FOUNDATIONAL NODES (Put these first)
# ==========================================

class ConditionNode(BaseModel):
    condition_description: str = Field(..., description="The logic or trigger required, e.g., 'Total Leverage Ratio <= 2.00 to 1.00'")
    reference_tags: Optional[List[str]] = Field(None, description="Any defined terms within the condition, e.g., ['[$REF: Total Leverage Ratio]']")

class SubLimitNode(BaseModel):
    category_name: str = Field(..., description="The specific category or carve-out, e.g., 'ERAS SPVs' or 'Subordinated Debt'")
    limit_amount: Union[float, str] = Field(..., description="The maximum dollar limit for this specific category.")
    conditions: Optional[List[ConditionNode]] = Field(None, description="Any conditions that must be met.")

# --> YOUR NEW NODE GOES HERE <--
class CarveOutNode(BaseModel):
    description: str = Field(..., description="The summary of the exception.")
    quantitative_limit: Optional[float] = Field(None, description="Extract any specific dollar or ratio limits mentioned within this exception. Output ONLY the float.")
    # Optional: You can also ask the agent to tag refs specific to this carve-out
    reference_tags: Optional[List[str]] = Field(None, description="Any defined terms within this specific exception, e.g., ['[$REF: Permitted Acquisition]']")


# ==========================================
# 2. THE UNIFIED HANDLER
# ==========================================

class UnifiedExceptions(BaseModel):
    """A dynamic schema that handles both inline lists and external references."""

    defined_term_refs: Optional[List[str]] = Field(
        None,
        description="If the covenant permits exceptions using a capitalized defined term, extract them here formatted exactly as [$REF: Exact Term Name]."
    )

    # --> UPDATED: Replaced List[str] with List[CarveOutNode] <--
    inline_list_summaries: Optional[List[CarveOutNode]] = Field(
        None,
        description="If the covenant explicitly lists exceptions directly in the text, extract each one as a separate object."
    )

# ==========================================
# 3. THE COVENANT SCHEMAS (Remain the same, but now inherit the new power)
# ==========================================

# --- 1. Total Leverage Ratio (Upgraded) ---
class LeverageStepDown(BaseModel):
    start_date: Optional[str] = Field(None)
    end_date: Optional[str] = Field(None)
    ratio_limit: Union[float, str] = Field(...)
    triggering_event: Optional[str] = Field(None, description="e.g., 'Prior to the Acceptable PPA Date'") # Catches the Hallador condition

class TotalLeverageIntermediate(BaseModel):
    is_false_flag: bool = Field(...)
    false_flag_reason: Optional[str] = Field(None)
    is_applicable: bool = Field(...)
    static_ratio_limit: Optional[Union[float, str]] = Field(None)
    step_downs: Optional[List[LeverageStepDown]] = Field(None) # Now supports conditional step-downs

# --- 2. Fixed Charge Coverage Ratio ---
class FixedChargeStep(BaseModel):
    start_date: Optional[str] = Field(None)
    end_date: Optional[str] = Field(None)
    ratio_limit: Union[float, str] = Field(...)

class FixedChargeIntermediate(BaseModel):
    is_false_flag: bool = Field(...)
    false_flag_reason: Optional[str] = Field(None)
    is_applicable: bool = Field(...)
    static_ratio_limit: Optional[Union[float, str]] = Field(None)
    step_ups: Optional[List[FixedChargeStep]] = Field(None, description="Step-ups or step-downs for the fixed charge ratio.")
    test_period: Optional[str] = Field(None)

# --- 3. Capital Expenditures ---
class CapExIntermediate(BaseModel):
    is_false_flag: bool = Field(...)
    false_flag_reason: Optional[str] = Field(None)
    is_applicable: bool = Field(...)
    annual_limit_amount: Optional[Union[float, str]] = Field(None, description="The maximum dollar amount permitted for CapEx per year.")
    carry_forward_permitted: Optional[bool] = Field(None, description="True if unused CapEx can be carried forward to the next year.")

# --- 4. Restricted Payments (Dividends/Distributions) (Upgraded) ---
class RestrictedPaymentsIntermediate(BaseModel):
    is_false_flag: bool = Field(...)
    false_flag_reason: Optional[str] = Field(None)
    is_applicable: bool = Field(...)
    general_basket_limit: Optional[Union[float, str]] = Field(None, description="The general dollar basket limit for restricted payments.")
    # NEW: Allow it to capture complex conditions like the Hallador Leverage/Liquidity trigger
    conditional_payments: Optional[List[SubLimitNode]] = Field(None, description="Extract any restricted payments that are only permitted if specific financial conditions or ratios are met.")

# --- 5. Investments & Acquisitions (Upgraded) ---
class InvestmentsIntermediate(BaseModel):
    is_false_flag: bool = Field(...)
    false_flag_reason: Optional[str] = Field(None)
    is_applicable: bool = Field(...)
    specific_carve_outs: Optional[List[SubLimitNode]] = Field(None, description="Extract EVERY distinct sub-limit category and dollar amount found in the section.") # Forces LLM to extract the $200M ERAS SPV

# --- 6. Debt Incurrence (Upgraded) ---
class DebtIntermediate(BaseModel):
    is_false_flag: bool = Field(...)
    false_flag_reason: Optional[str] = Field(None)
    is_applicable: bool = Field(...)
    # UPDATED: Removed flat capital_lease_limit. Replaced with dynamic array to catch Subordinated Debt, Capital Leases, etc.
    specific_carve_outs: Optional[List[SubLimitNode]] = Field(None, description="Extract EVERY distinct debt sub-limit category (e.g., Capital Leases, Subordinated Debt) and its dollar amount.")

# --- 7. Reporting Requirements (Upgraded) ---
class ReportingIntermediate(BaseModel):
    is_false_flag: bool = Field(...)
    false_flag_reason: Optional[str] = Field(None)
    is_applicable: bool = Field(...)
    # FORCING STRICT TYPES: Removed 'str' from the Union.
    annual_financials_days: Optional[int] = Field(None, description="Extract ONLY the integer representing the number of days.")
    quarterly_financials_days: Optional[int] = Field(None, description="Extract ONLY the integer representing the number of days.")

# --- 8. Limitation on Liens ---
class LiensIntermediate(BaseModel):
    """Phase 1 Extraction schema for Limitation on Liens."""
    is_false_flag: bool = Field(..., description="Set to True ONLY IF the text is a cross-reference or lacks the actual covenant definition.")
    false_flag_reason: Optional[str] = Field(None)
    is_applicable: bool = Field(..., description="True if the text contains a valid restriction on liens.")

    # We nest the unified handler inside the main schema
    exceptions: Optional[UnifiedExceptions] = Field(None)

# --- 9. Mergers, Consolidations, Etc. ---
class MergersIntermediate(BaseModel):
    """Phase 1 Extraction schema for Mergers and Consolidations."""
    is_false_flag: bool = Field(...)
    false_flag_reason: Optional[str] = Field(None)
    is_applicable: bool = Field(..., description="True if the text restricts mergers, consolidations, or liquidations.")

    # We nest the unified handler inside the main schema
    exceptions: Optional[UnifiedExceptions] = Field(None)

class CovenantIntermediate(BaseModel):
    is_false_flag: bool = Field(...)
    is_applicable: bool = Field(...)

    # We nest the unified handler inside the main schema
    exceptions: Optional[UnifiedExceptions] = Field(None)

# --- Master System Prompt ---
MASTER_SYSTEM_PROMPT = """
You are an expert Commercial Credit Analyst and Principal Data Extraction Agent specializing in LSTA syndicated loan agreements.

Your current assignment is to act as the {agent_name} extraction agent.

GUARDRAIL DEFINITION:
You are strictly looking for data that matches this definition: "{guardrail}"

YOUR TASK:
Analyze the provided 'Payload_Text'. Your goal is to extract the highly structured parameters and map them precisely to the JSON schema.

CRITICAL PROTOCOLS:
1. THE AGENT ABORT (is_false_flag): If the text DOES NOT contain the actual operational limits, dates, or financial mechanics of the covenant, you MUST set "is_false_flag": true and provide a brief "false_flag_reason".
2. MISSING VARIABLES: If a limit or term is capitalized and defined elsewhere in the document, DO NOT GUESS. You must extract it exactly as a reference tag formatted like this: [$REF: Exact Term Name].
3. PRECISION: Only extract what is explicitly written in the Payload_Text. Do not infer standard market terms if they are not present.
4. EXHAUSTIVE EXTRACTION: If the schema contains a list or array (e.g., 'specific_carve_outs' or 'step_downs'), you MUST extract EVERY instance found in the text. Do not stop at the first match. If multiple distinct limits or categories exist, create a new object in the array for each one.
5. SENTINEL VALUES: If a dollar basket is explicitly uncapped or "Unlimited", you MUST extract the float as `-1.0`. If a limit is "Not Applicable" or omitted, extract `0.0`. Never extract strings for quantitative limits.

PAYLOAD TEXT TO ANALYZE:
"{payload_text}"
"""

"""Calling on Agents to do Extraction"""

import json
import time

# --- 1. Configuration & Current Pricing Constants ---
EXTRACTION_MODEL = 'gemini-3.1-flash-lite'

# Current pricing for Gemini 3.1 Flash-Lite (USD per 1 Million tokens)
INPUT_PRICE_PER_MILLION = 0.25
OUTPUT_PRICE_PER_MILLION = 1.50

# --- 2. Modular Cost Calculator ---
def calculate_api_cost(usage_metadata):
    """Calculates the exact cost based on Gemini 3.1 Flash-Lite rates."""
    input_tokens = usage_metadata.prompt_token_count
    output_tokens = usage_metadata.candidates_token_count
    total_tokens = usage_metadata.total_token_count

    input_cost = (input_tokens / 1_000_000) * INPUT_PRICE_PER_MILLION
    output_cost = (output_tokens / 1_000_000) * OUTPUT_PRICE_PER_MILLION
    total_cost = input_cost + output_cost

    return {
        "input_tokens": input_tokens,
        "output_tokens": output_tokens,
        "total_tokens": total_tokens,
        "input_cost_usd": input_cost,
        "output_cost_usd": output_cost,
        "total_cost_usd": total_cost
    }

# --- 3. Load the Dispatch Queue ---
file_path = 'dispatch_queue_output.json'
try:
    with open(file_path, 'r') as file:
        dispatch_queue = json.load(file)
    print(f"Successfully loaded {len(dispatch_queue)} envelopes from the queue.\n")
except FileNotFoundError:
    print(f"Error: Could not find {file_path}. Ensure it is uploaded to your Colab environment.")
    dispatch_queue = []

# --- 4. The Schema Router ---
schema_router = {
    "TotalLeverageRatio": TotalLeverageIntermediate,
    "FixedChargeCoverageRatio": FixedChargeIntermediate,
    "CapitalExpenditures": CapExIntermediate,
    "RestrictedPayments": RestrictedPaymentsIntermediate,
    "InvestmentsAndAcquisitions": InvestmentsIntermediate,
    "DebtIncurrence": DebtIntermediate,
    "ReportingRequirements": ReportingIntermediate,
    "LimitationOnLiens": LiensIntermediate,
    "MergersAndConsolidations": MergersIntermediate
}

# --- 5. The Execution Loop ---
results_database = []
total_pipeline_cost = 0.0

for index, envelope in enumerate(dispatch_queue):
    agent_name = envelope.get("Agent")

    # Safety Check: Skip if we haven't built the schema yet
    if agent_name not in schema_router:
        print(f"[{index}] Skipping {agent_name}... Schema not yet built.")
        continue

    print(f"[{index}] Processing Envelope: {agent_name}")
    print(f"    Receipt: {envelope.get('Receipt')}")

    target_schema = schema_router[agent_name]
    raw_text = envelope.get("Payload_Text", "")
    clean_text = raw_text.replace('\n', ' ').replace('\xa0', ' ')

    formatted_prompt = MASTER_SYSTEM_PROMPT.format(
        agent_name=agent_name,
        guardrail=envelope.get("Definition_Guardrail", ""),
        payload_text=clean_text
    )

    # Make the API Call
    try:
        response = client.models.generate_content(
            model=EXTRACTION_MODEL,
            contents=formatted_prompt,
            config={
                'response_mime_type': 'application/json',
                'response_schema': target_schema,
                'temperature': 0.0 # Strict extraction
            },
        )

        # Extract Data & Calculate Usage Metrics
        extracted_data = response.parsed
        cost_metrics = calculate_api_cost(response.usage_metadata)
        total_pipeline_cost += cost_metrics['total_cost_usd']

        results_database.append({
            "Receipt": envelope.get("Receipt"),
            "Agent": agent_name,
            "Extracted_Data": extracted_data.model_dump(),
            "Cost_Metrics": cost_metrics
        })

        print("    Status: Extraction Successful")
        print(f"    Tokens: {cost_metrics['input_tokens']} In | {cost_metrics['output_tokens']} Out")
        print(f"    Cost:   ${cost_metrics['total_cost_usd']:.6f}")
        print("    Extracted Payload:")
        print(json.dumps(extracted_data.model_dump(), indent=2))
        print("\n" + "-"*40 + "\n")

    except Exception as e:
        print(f"    Status: FAILED. Error: {e}\n")

    time.sleep(2) # Brief pause for rate limits

# --- 6. Save the Output ---
output_filename = 'phase1_extracted_nodes.json'
print(f"Finished processing. Successfully extracted {len(results_database)} covenants.")
print(f"Total Pipeline API Cost: ${total_pipeline_cost:.6f}\n")

if results_database:
    with open(output_filename, 'w') as outfile:
        json.dump(results_database, outfile, indent=4)
    print(f"Extraction complete. Data successfully saved to {output_filename}.")
else:
    print("No covenants extracted. File not saved.")

"""Building the Glossary"""

import re
import json
import pandas as pd
from datetime import datetime

def build_deterministic_glossary(article_1_text: str) -> dict:
    """
    Sweeps Article 1 to extract every definition and statically maps
    nested references using strict Regex boundaries. Zero AI tokens used.
    """
    print("Initializing Pure Code Glossary Engine...")

    # 1. Find all definition start points
    # Pattern: "Term" means...
    pattern = r'["“”]([^"“”]+)["“”]\s*(?:of\s+a\s+Person)?\s*means'
    matches = list(re.finditer(pattern, article_1_text, re.IGNORECASE))

    raw_glossary = {}

    # 2. Extract the full text block for each definition
    for i, match in enumerate(matches):
        term = match.group(1).strip()
        start_idx = match.start()

        # The text for this term ends exactly where the next term begins
        end_idx = matches[i+1].start() if i + 1 < len(matches) else len(article_1_text)

        # Clean up whitespace and line breaks
        raw_definition_text = article_1_text[start_idx:end_idx].strip()
        raw_glossary[term] = raw_definition_text

    print(f"  -> Extracted {len(raw_glossary)} raw definitions from text.")

    # 3. Link Nested References (The pure code linker)
    final_glossary = {}
    all_terms = list(raw_glossary.keys())

    # Sort terms by length descending (e.g., check "Consolidated Net Income" before "Net Income")
    all_terms.sort(key=len, reverse=True)

    print("  -> Executing deterministic reference mapping...")
    for term, text in raw_glossary.items():
        nested_refs = set()

        for potential_target in all_terms:
            if potential_target == term:
                continue # Do not self-reference

            # Strict boundary (\b) and exact case match
            # This ensures we don't match "Law" inside "Lawsuit"
            escape_term = re.escape(potential_target)
            if re.search(rf'\b{escape_term}\b', text):
                nested_refs.add(potential_target)

        final_glossary[term] = {
            "raw_definition_text": text,
            "nested_references": list(nested_refs)
        }

    return final_glossary

# --- Execution Block ---
if __name__ == "__main__":
    csv_file_path = "final_extracted_covenants_phase1_payload.csv"
    output_file = "resolved_definitions.json"

    try:
        # Load Phase 0 Data
        df = pd.read_csv(csv_file_path)
        article_1_df = df[df['Article'].astype(str).str.contains('Article 1', case=False, na=False)]
        real_article_1_text = " ".join(article_1_df['Raw_Text'].dropna().tolist())
        print(f"Successfully loaded {len(real_article_1_text)} characters of Article 1 text.\n")

        # Execute the Engine
        start_time = datetime.now()
        master_glossary = build_deterministic_glossary(real_article_1_text)
        end_time = datetime.now()

        # Save output
        with open(output_file, 'w', encoding='utf-8') as out:
            json.dump(master_glossary, out, indent=2)

        execution_time = (end_time - start_time).total_seconds()
        print(f"\nPhase 2 Complete!")
        print(f"Total API Cost: $0.00")
        print(f"Execution Time: {execution_time:.3f} seconds")
        print(f"Payload saved to: {output_file}")

    except FileNotFoundError:
        print(f"Error: Could not find '{csv_file_path}'.")
    except Exception as e:
        print(f"Error executing script: {e}")

"""Relational Compiler"""

import json
import re
import difflib
import pandas as pd
from datetime import datetime
from typing import Dict, List, Any

class MultiHopRelationalCompiler:
    """
    Phase 2: Enterprise-Grade Relational Linker (Node F).
    Executes a Multi-Hop resolution strategy.
    If a term is found in an external section (like Events of Default),
    it dynamically injects that section into the Master Glossary to simplify the UI.
    """

    def __init__(self, phase2_glossary_path: str, document_chunks_csv_path: str):
        self.ref_pattern = re.compile(r'\[\$REF:\s*([^\]]+)\]')
        self.dangling_pointers = set()

        self.master_glossary = self._load_json(phase2_glossary_path)
        self.glossary_keys = list(self.master_glossary.keys())
        self.glossary_keys_lower = {k.lower(): k for k in self.glossary_keys}

        print(f"Loading TOC routing chunks from {document_chunks_csv_path}...")
        try:
            chunk_df = pd.read_csv(document_chunks_csv_path)
            raw_chunks = chunk_df.to_dict(orient='records')
            self.toc_routing_index = self._build_toc_routing_index(raw_chunks)
        except FileNotFoundError:
            raise FileNotFoundError(f"CRITICAL: Could not find Phase 0 chunks at {document_chunks_csv_path}")

    def _load_json(self, filepath: str) -> Any:
        try:
            with open(filepath, 'r', encoding='utf-8') as f:
                return json.load(f)
        except FileNotFoundError:
            raise FileNotFoundError(f"CRITICAL: Failed to load {filepath}")

    def _build_toc_routing_index(self, chunks: List[Dict]) -> Dict[str, Dict]:
        toc_index = {}
        for chunk in chunks:
            section_title = chunk.get('Section_Title')
            if not isinstance(section_title, str) or not section_title.strip():
                continue

            clean_title = section_title.strip().lower()
            semantic_title = re.sub(r'section\s*\d+\.\d+\s*', '', clean_title).strip()

            toc_index[semantic_title] = {
                "routing_type": "External Section Router",
                "location": f"{chunk.get('Article_Title', 'Unknown Article')} | {section_title}",
                "extracted_text": str(chunk.get('Raw_Text', 'Text unavailable.'))
            }

        print(f" -> Successfully built TOC Routing Index with {len(toc_index)} operational sections.")
        return toc_index

    def _resolve_term(self, raw_term: str) -> str:
        clean_term = raw_term.strip()
        lower_term = clean_term.lower()

        # ==========================================
        # HOP 1: Exact Match in Article 1
        # ==========================================
        if clean_term in self.glossary_keys:
            return clean_term

        # ==========================================
        # HOP 2: Multi-Hop Injection (PoC Scope Fix)
        # Instead of routing, we inject the section directly into the glossary.
        # ==========================================

        # 2a. Exact TOC Match
        if lower_term in self.toc_routing_index:
            print(f"  [Multi-Hop] Injected external section into Glossary: '[$REF: {raw_term}]'")

            # Inject the raw section text directly into the master glossary dictionary
            self.master_glossary[clean_term] = {
                "raw_definition_text": self.toc_routing_index[lower_term]["extracted_text"],
                "nested_references": [] # Kept empty to prevent circular loops in external sections
            }
            self.glossary_keys.append(clean_term)
            return clean_term

        # 2b. Fuzzy TOC Match
        toc_keys = list(self.toc_routing_index.keys())
        toc_matches = difflib.get_close_matches(lower_term, toc_keys, n=1, cutoff=0.85)

        if toc_matches:
            best_toc = toc_matches[0]
            print(f"  [Multi-Hop] Fuzzy injected external section into Glossary: '[$REF: {raw_term}]'")

            self.master_glossary[clean_term] = {
                "raw_definition_text": self.toc_routing_index[best_toc]["extracted_text"],
                "nested_references": []
            }
            self.glossary_keys.append(clean_term)
            return clean_term

        # ==========================================
        # HOP 3: Base Word Strip
        # ==========================================
        base_term = clean_term[:-1] if lower_term.endswith('s') else clean_term
        if base_term in self.glossary_keys:
            print(f"  [Linker] Fixed Plural: '[$REF: {raw_term}]' -> '[$REF: {base_term}]'")
            return base_term

        # ==========================================
        # HOP 4: Fuzzy Semantic Match
        # ==========================================
        close_matches = difflib.get_close_matches(clean_term, self.glossary_keys, n=1, cutoff=0.8)
        if close_matches:
            best_match = close_matches[0]
            print(f"  [Linker] Fuzzy Matched: '[$REF: {raw_term}]' -> '[$REF: {best_match}]'")
            return best_match

        # ==========================================
        # HOP 5: Dangling Pointer
        # ==========================================
        self.dangling_pointers.add(raw_term)
        print(f"  [WARNING] Dangling Pointer: Could not link '[$REF: {raw_term}]'")
        return raw_term

    def _process_string(self, text: str) -> str:
        matches = self.ref_pattern.findall(text)
        for raw_term in matches:
            resolved_key = self._resolve_term(raw_term)
            if resolved_key != raw_term:
                text = text.replace(f"[$REF: {raw_term}]", f"[$REF: {resolved_key}]")
        return text

    def _traverse_and_mutate(self, node: Any):
        if isinstance(node, dict):
            for key, value in node.items():
                if isinstance(value, str):
                    node[key] = self._process_string(value)
                else:
                    self._traverse_and_mutate(value)
        elif isinstance(node, list):
            for i, value in enumerate(node):
                if isinstance(value, str):
                    node[i] = self._process_string(value)
                else:
                    self._traverse_and_mutate(value)

    def compile(self, phase1_data_path: str, output_path: str):
        print("\nInitializing Enterprise Relational Compiler...")
        phase1_covenants = self._load_json(phase1_data_path)

        print("\nExecuting Deep Relational Linking (Dynamic Injection Enabled)...")
        self._traverse_and_mutate(phase1_covenants)

        compiled_payload = {
            "Document_Metadata": {
                "Processing_Timestamp": datetime.now().isoformat(),
                "Pipeline_Version": "Enterprise_v3.1_Injection",
                "Audit_Status": "Warnings_Detected" if self.dangling_pointers else "Clean",
                "Total_Definitions_Resolved": len(self.master_glossary),
                "Dangling_Pointers_Detected": list(self.dangling_pointers)
            },
            "Phase1_Extracted_Covenants": phase1_covenants,
            "Phase2_Master_Glossary": self.master_glossary
        }

        with open(output_path, 'w', encoding='utf-8') as out:
            json.dump(compiled_payload, out, indent=4)

        print(f"\nCompilation Complete. Payload saved to: {output_path}")
        if not self.dangling_pointers:
            print("Audit Status: CLEAN. Zero dangling pointers.")
        else:
            print(f"Audit Status: WARNING. {len(self.dangling_pointers)} pointers could not be resolved.")

if __name__ == "__main__":
    try:
        compiler = MultiHopRelationalCompiler(
            phase2_glossary_path="resolved_definitions.json",
            document_chunks_csv_path="final_extracted_covenants_phase1_payload.csv"
        )
        compiler.compile(
            phase1_data_path="phase1_extracted_nodes.json",
            output_path="final_compiled_payload.json"
        )
    except Exception as e:
        print(f"\nPIPELINE EXECUTION FAILED: {str(e)}")

"""Audit"""

import json
import re
import time

def run_database_audit(payload_path: str):
    """
    Acts as an independent auditor to verify the relational integrity
    and computational safety of the final JSON payload.
    """
    print("==================================================")
    print("Initializing Phase 3 Validation Gate...")
    print("==================================================\n")

    start_time = time.time()

    try:
        with open(payload_path, 'r', encoding='utf-8') as f:
            payload = json.load(f)
            print(f"[System] Successfully loaded {payload_path}")
    except FileNotFoundError:
        print(f"[Error] Could not find {payload_path}")
        return

    covenants = payload.get("Phase1_Extracted_Covenants", [])
    glossary = payload.get("Phase2_Master_Glossary", {})

    warnings = {
        "Dangling_Pointers": [],
        "Circular_References": [],
        "Type_Violations": []
    }

    # --- 1. Audit for Circular References (Optimized DFS) ---
    print("\n[Audit 1/3] Sweeping for Circular References...")
    circular_loops = set()
    global_visited = set() # MEMOIZATION: Tracks terms we have fully cleared

    def dfs(current_term, current_path):
        if current_term not in glossary:
            return

        # If we already proved this term is safe in a previous loop, skip it
        if current_term in global_visited:
            return

        for nested_term in glossary[current_term].get("nested_references", []):
            if nested_term in current_path:
                loop_idx = current_path.index(nested_term)
                loop = current_path[loop_idx:] + [nested_term]
                circular_loops.add(" -> ".join(loop))
            else:
                dfs(nested_term, current_path + [nested_term])

        # Once we finish checking all children of this term, mark it as safe
        global_visited.add(current_term)

    terms_list = list(glossary.keys())
    total_terms = len(terms_list)

    for i, term in enumerate(terms_list):
        # Progress Update every 50 terms
        if i > 0 and i % 50 == 0:
            print(f"  ... Checked {i}/{total_terms} definitions...")
        dfs(term, [term])

    warnings["Circular_References"] = list(circular_loops)
    if circular_loops:
        print(f"  [WARNING] Found {len(circular_loops)} circular loops. Bypassed successfully.")
    else:
        print("  [PASS] No circular references detected.")

    # --- 2. Post-Compilation Pointer Audit ---
    print("\n[Audit 2/3] Auditing Phase 1 Pointers...")
    ref_pattern = re.compile(r'\[\$REF:\s*([^\]]+)\]')
    pointer_count = {"checked": 0}

    def find_pointers(node):
        if isinstance(node, dict):
            for value in node.values():
                find_pointers(value)
        elif isinstance(node, list):
            for item in node:
                find_pointers(item)
        elif isinstance(node, str):
            for match in ref_pattern.findall(node):
                pointer_count["checked"] += 1
                if match not in glossary:
                    warnings["Dangling_Pointers"].append(match)

    find_pointers(covenants)
    warnings["Dangling_Pointers"] = list(set(warnings["Dangling_Pointers"]))

    if warnings["Dangling_Pointers"]:
        print(f"  [FAIL] Found {len(warnings['Dangling_Pointers'])} dangling pointers.")
    else:
        print(f"  [PASS] All {pointer_count['checked']} pointers perfectly resolved.")

    # --- 3. Audit for Type Violations ---
    print("\n[Audit 3/3] Auditing Quantitative Data Types...")
    type_violation_count = 0

    for cov in covenants:
        data = cov.get("Extracted_Data", {})
        for key, value in data.items():
            if "limit" in key and value is not None:
                if not isinstance(value, (int, float)):
                    warnings["Type_Violations"].append(
                        f"{cov.get('Agent')} -> {key} is a {type(value).__name__} (Expected int/float)"
                    )
                    type_violation_count += 1

    if type_violation_count > 0:
        print(f"  [FAIL] Found {type_violation_count} mathematical type violations.")
    else:
        print("  [PASS] All limits are strictly numeric (int/float).")

    # --- Compile the Final Report ---
    total_warnings = sum(len(v) for v in warnings.values())
    payload["Document_Metadata"]["Audit_Status"] = "Clean" if total_warnings == 0 else "Warnings_Detected"
    payload["Document_Metadata"]["Warnings"] = warnings

    with open(payload_path, 'w', encoding='utf-8') as out:
        json.dump(payload, out, indent=2)

    end_time = time.time()
    print("\n==================================================")
    print(f"Audit Complete in {(end_time - start_time):.3f} seconds.")
    print(f"Final Status: {payload['Document_Metadata']['Audit_Status']}")
    print("==================================================")

# --- Execution ---
if __name__ == "__main__":
    run_database_audit("final_compiled_payload.json")

"""Rater Agent (Sanity Check built in via Chaos Module)"""

import os
import json
import time
import pandas as pd
from google import genai
from google.colab import userdata
from pydantic import BaseModel, Field
from typing import List, Optional, Tuple, Dict, Any

# ==========================================
# MODULE 1: CONFIGURATION & SCHEMAS
# ==========================================

EXTRACTION_MODEL = 'gemini-3.1-flash-lite'
INPUT_PRICE_PER_MILLION = 0.25
OUTPUT_PRICE_PER_MILLION = 1.50

AUDITOR_SYSTEM_PROMPT = """
You are an expert Legal Proofreader and Data Provenance Auditor.
Your sole objective is to verify that the provided 'Extracted_JSON' perfectly matches the factual reality of the 'Raw_Source_Text'.

CRITICAL DIRECTIVES:
1. DO NOT RECALCULATE: You are not a financial analyst. Do not interpret intent, recalculate formulas, or infer market standards.
2. STRICT MATCHING (ALL DATA TYPES): You must verify EVERY value (numbers, strings, and [$REF] tags). If a value contains a string modifier (e.g., "PROHIBITED", "NOT", "FALSE"), that modifier MUST explicitly exist in the raw text. Do not ignore text attached to numbers.
3. SENTINEL AWARENESS: The extraction agent uses `-1.0` to mean "Unlimited" or "Uncapped", and `0.0` to mean "None" or "Not Applicable". If you see these values in the JSON, do not look for the literal numbers; instead, verify that the text semantically states the limit is unlimited/uncapped or does not exist.
4. SILENT HALLUCINATIONS: Pay extreme attention to decimals, dates, pluralizations, and legally restrictive words.

Raw_Source_Text:
"{raw_text}"

Extracted_JSON_To_Audit:
{json_payload}
"""

class ValidationAudit(BaseModel):
    """Schema for the Node L LLM-as-a-Judge output."""
    is_verified: bool = Field(
        ...,
        description="True ONLY if every numerical value and [$REF] tag perfectly matches the source text."
    )
    confidence_score: float = Field(
        ...,
        description="A DATA FIDELITY SCORE from 0.0 to 1.0. If is_verified is True, score is 1.0. If you find ANY hallucination, error, or discrepancy, you MUST lower this score. (e.g., 0.8 for a minor typo, 0.5 for a wrong number, 0.0 for a complete hallucination)."
    )
    requires_human_context: bool = Field(
        ...,
        description="True if the source text is inherently ambiguous, contradictory, or relies on an external schedule not present in the text."
    )
    flagged_discrepancies: Optional[List[str]] = Field(
        None,
        description="If is_verified is False, provide a detailed list explaining exactly which keys failed and why."
    )

# ==========================================
# MODULE 2: UTILITIES & AUTHENTICATION
# ==========================================

def initialize_client() -> genai.Client:
    """Fetches credentials securely and initializes the GenAI client."""
    os.environ["GEMINI_API_KEY"] = userdata.get('FreeTierGeminKey')
    return genai.Client()

def calculate_api_cost(usage_metadata) -> Dict[str, float]:
    """Calculates the exact cost based on token usage and model rates."""
    input_tokens = usage_metadata.prompt_token_count
    output_tokens = usage_metadata.candidates_token_count
    total_tokens = usage_metadata.total_token_count

    input_cost = (input_tokens / 1_000_000) * INPUT_PRICE_PER_MILLION
    output_cost = (output_tokens / 1_000_000) * OUTPUT_PRICE_PER_MILLION

    return {
        "input_tokens": input_tokens,
        "output_tokens": output_tokens,
        "total_tokens": total_tokens,
        "total_cost_usd": input_cost + output_cost
    }

# ==========================================
# MODULE 3: DATA INGESTION & REHYDRATION
# ==========================================

def load_pipeline_data(csv_path: str, json_path: str) -> Tuple[pd.DataFrame, Dict[str, Any], List[Dict[str, Any]]]:
    """Loads the raw text CSV and the compiled JSON payload."""
    try:
        df_raw = pd.read_csv(csv_path)
        with open(json_path, 'r') as file:
            compiled_data = json.load(file)
        covenants_list = compiled_data.get("Phase1_Extracted_Covenants", [])
        print(f"Successfully loaded CSV and {len(covenants_list)} compiled covenants.\n")
        return df_raw, compiled_data, covenants_list
    except FileNotFoundError as e:
        print(f"Error loading files: {e}. Please ensure files are in the working directory.")
        return pd.DataFrame(), {}, []

def build_rehydration_db(df_raw: pd.DataFrame) -> Dict[str, str]:
    """
    Reconstructs the composite Receipt string from the CSV to act as a primary key.
    Normalizes whitespace to prevent encoding drift during the join.
    """
    if df_raw.empty:
        return {}

    def build_receipt_string(row):
        return f"PDF Pages {row['Absolute_Start_Page']}-{row['Absolute_End_Page']} (Printed Pages {row['Printed_Start_Page']}-{row['Printed_End_Page']}) | {row['Article']}: {row['Article_Title']} | {row['Section']}: {row['Section_Title']}"

    df_raw['Reconstructed_Receipt'] = df_raw.apply(build_receipt_string, axis=1)

    # Strict normalization to prevent join failures
    df_raw['Reconstructed_Receipt'] = df_raw['Reconstructed_Receipt'].astype(str).str.strip().str.replace(r'\s+', ' ', regex=True)

    return dict(zip(df_raw['Reconstructed_Receipt'], df_raw['Raw_Text']))

# ==========================================
# MODULE 4: THE AUDIT ENGINE
# ==========================================

def apply_chaos_injection(agent_name: str, data_to_audit: Dict[str, Any]) -> None:
    """
    Advanced Adversarial Chaos Engine.
    Injects specific types of errors (Math, Legal Strings, Reference Tags)
    to guarantee Node L is rigorously auditing the text.
    """
    # 1. MATH CHAOS: Altering a nested float
    if agent_name == "TotalLeverageRatio" and data_to_audit.get("step_downs"):
        try:
            original = data_to_audit["step_downs"][0]["ratio_limit"]
            data_to_audit["step_downs"][0]["ratio_limit"] = 9.99
            print(f"    -> [!] CHAOS (MATH): Corrupted {original} -> 9.99")
        except (IndexError, KeyError):
            pass

    # 2. SEMANTIC CHAOS: The "Sneaky Negation" in text
    elif agent_name == "RestrictedPayments" and "general_basket_limit" in data_to_audit:
        try:
            # We add a legally dangerous word that isn't in the raw text
            original = str(data_to_audit["general_basket_limit"])
            data_to_audit["general_basket_limit"] = f"PROHIBITED {original}"
            print(f"    -> [!] CHAOS (SEMANTIC): Injected dangerous legal negation.")
        except KeyError:
            pass

    # 3. GRAPH CHAOS: Sabotaging a cross-reference tag
    elif agent_name == "InvestmentsAndAcquisitions":
        try:
            if "specific_carve_outs" in data_to_audit and len(data_to_audit["specific_carve_outs"]) > 0:
                carve_out = data_to_audit["specific_carve_outs"][0]
                if "category_name" in carve_out:
                    original = carve_out["category_name"]
                    carve_out["category_name"] = original + " AND FAKE TERM"
                    print(f"    -> [!] CHAOS (GRAPH): Sabotaged term name -> '{carve_out['category_name']}'")
        except (IndexError, KeyError):
            pass

def execute_llm_audit(client: genai.Client, raw_text: str, data_to_audit: Dict[str, Any]) -> Tuple[Dict[str, Any], float]:
    """Formats the prompt, calls the LLM at 0.0 temperature, and returns the audit result and cost."""
    formatted_prompt = AUDITOR_SYSTEM_PROMPT.format(
        raw_text=str(raw_text).replace('\n', ' ').replace('\xa0', ' '),
        json_payload=json.dumps(data_to_audit, indent=2)
    )

    response = client.models.generate_content(
        model=EXTRACTION_MODEL,
        contents=formatted_prompt,
        config={
            'response_mime_type': 'application/json',
            'response_schema': ValidationAudit,
            'temperature': 0.0  # Maximum determinism
        },
    )

    audit_result = response.parsed.model_dump()
    cost_metrics = calculate_api_cost(response.usage_metadata)

    return audit_result, cost_metrics['total_cost_usd']

# ==========================================
# MODULE 5: ORCHESTRATION (THE PIPELINE)
# ==========================================

def run_validation_pipeline(csv_path: str, json_path: str, output_path: str, enable_adversarial_test: bool = False):
    """Main orchestrator function that executes the Node L validation loop."""
    client = initialize_client()
    df_raw, compiled_data, covenants_list = load_pipeline_data(csv_path, json_path)

    if not covenants_list:
        return

    text_lookup_db = build_rehydration_db(df_raw)
    total_audit_cost = 0.0

    for index, covenant_node in enumerate(covenants_list):
        # 1. Normalize the incoming JSON receipt key
        receipt_key = str(covenant_node.get("Receipt", "")).strip()
        receipt_key = " ".join(receipt_key.split())

        agent_name = covenant_node.get("Agent")
        extracted_data = covenant_node.get("Extracted_Data", {})
        print(f"[{index}] Auditing Node: {agent_name}")

        # 2. Rehydrate Raw Text
        raw_text = text_lookup_db.get(receipt_key)
        if not raw_text:
            print(f"    -> WARNING: Could not rehydrate text for Receipt: {receipt_key}")
            covenant_node["Validation_Audit"] = {
                "is_verified": False,
                "confidence_score": 0.0,
                "requires_human_context": True,
                "flagged_discrepancies": ["PIPELINE ERROR: Failed to join JSON Receipt to CSV Raw_Text."]
            }
            continue

        # 3. Targeted Key Stripping (Remove operational pipeline flags)
        data_to_audit = {k: v for k, v in extracted_data.items() if k not in ["is_applicable", "is_false_flag", "false_flag_reason"]}

        if not any(data_to_audit.values()):
            print("    -> Status: Skipped (No quantitative data to audit).")
            covenant_node["Validation_Audit"] = {
                "is_verified": True,
                "confidence_score": 1.0,
                "requires_human_context": False,
                "flagged_discrepancies": None
            }
            continue

        # 4. Optional Adversarial Testing
        if enable_adversarial_test:
            apply_chaos_injection(agent_name, data_to_audit)

        # 5. Execute LLM Audit
        try:
            audit_result, call_cost = execute_llm_audit(client, raw_text, data_to_audit)
            total_audit_cost += call_cost

            # Non-Destructive Append
            covenant_node["Validation_Audit"] = audit_result

            print("    -> Status: Audit Complete")
            print(f"    -> Verified: {audit_result['is_verified']} | Confidence: {audit_result['confidence_score']}")
            if not audit_result['is_verified'] and audit_result['flagged_discrepancies']:
                print(f"    -> FLAGS: {audit_result['flagged_discrepancies']}")

        except Exception as e:
            print(f"    -> Status: FAILED API CALL. Error: {e}")
            covenant_node["Validation_Audit"] = {
                "is_verified": False,
                "confidence_score": 0.0,
                "requires_human_context": True,
                "flagged_discrepancies": [f"API ERROR: {str(e)}"]
            }

        time.sleep(2) # Rate limit padding

    # 6. Save Payload
    with open(output_path, 'w') as outfile:
        json.dump(compiled_data, outfile, indent=4)

    print(f"\nAudit complete. Data successfully saved to {output_path}.")
    print(f"Total Exception Layer API Cost: ${total_audit_cost:.6f}")

# ==========================================
# EXECUTION
# ==========================================
if __name__ == "__main__":
    run_validation_pipeline(
        csv_path='final_extracted_covenants_phase1_payload.csv',
        json_path='final_compiled_payload.json',
        output_path='final_compiled_payload_audited.json',
        enable_adversarial_test=True # Set to False for production
    )

